name: CI-CD
env:
  EB_PACKAGE_S3_BUCKET_NAME : "elasticbeanstalk-eu-central-1-515545681481"
  EB_APPLICATION_NAME       : "Simple"
  EB_ENVIREMENT_NAME        : "Simple-env"
  DEPLOY_PACKAGE_NAME       : "simple_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-central-1"
     
on:
  push:
    branches: master

jobs:
  my_ci:

    runs-on: ubuntu-latest

    steps:
    - name: Git clone my repo
      uses: actions/checkout@v1
      
    - name: create zip deployment package
      run :  zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
    
    - name: Configure my AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id     : ${{ secrets.AWS_ACCESS_ID }}
        aws-secret-access-key : ${{ secrets.AWS_ACCESS_KEY }}
        aws-region            : ${{ env.AWS_REGION_NAME }} 
    
    - name: Copy my files into s3 bucket
      run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
      
    - name: Print Happy message for CI
      run : echo "CI pipeline part finished successfully"
